import type { Project } from '../types'
import { renderProject } from './renderer'

/**
 * Build an Online Store 2.0 section `.liquid` file wrapping the Shopify fragment in `{% raw %}`.
 * HTML containing `{% endraw %}` will break Liquid — re-export after fixing.
 *
 * 将 Shopify 片段包在 `{% raw %}` 中的 OS 2.0 `sections/*.liquid` 文件；若 HTML 内含 `{% endraw %}` 会破坏 Liquid。
 */
export function buildShopifySectionLiquidFile(project: Project): string {
  const fragment = project.sections.length === 0 ? '' : renderProject(project)
  const schemaJson = `{
  "name": "IC Builder export",
  "tag": "section",
  "class": "ic-builder-section",
  "settings": [],
  "presets": [
    {
      "name": "IC Builder export"
    }
  ]
}`
  return `{% comment %}
  Generated by Shopify HTML Builder. Edit in the app and re-download, or paste updated HTML from Export.
{% endcomment %}
{% raw %}
${fragment}
{% endraw %}
{% schema %}
${schemaJson}
{% endschema %}
`
}
